site_name: gpac
theme:
  name: readthedocs
#  include_sidebar: true
#  navigation_depth: 1  # Controls how deep the TOC goes
#  collapse_navigation: false  # Show all sections, not just the current page
#  sticky_navigation: true  # Makes the sidebar scroll with the pages

extra_css:
  - style.css

# Add watch directive to monitor Python source files
watch:
  - docs
  - mkdocs.yaml
  - gpac

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            rendering:
              line_length: 100
            members_order: source
            signature_crossrefs: true
            show_if_no_docstring: false
            separate_signature: true
            show_signature_annotations: true
            docstring_section_style: table
            show_symbol_type_heading: true
            docstring_style: numpy
            show_source: true

#plugins:
#  - search
#  - mkdocstrings:
#      default_handler: python
#      handlers:
#        python:
#          options:
#            members_order: source
#            signature_crossrefs: true
#            show_if_no_docstring: false
#            separate_signature: true
#            show_signature_annotations: true
#            docstring_section_style: table
#            show_symbol_type_heading: true
#            docstring_style: numpy
#            line_length: 100
#            show_source: true

#plugins:
#  - search
#  - autorefs
#  - mkdocstrings:
#      handlers:
#        python:
#          # Use the extended handler instead of the default one
##          handler: python_xref
#          # Regular mkdocstrings options go here
#          options:
#            show_source: true
#            show_root_heading: true
            
nav:
  - Home: index.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

# This is needed to render Latex even though we included arithmatex above.
extra_javascript:
  - mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js