site_name: gpac
theme: material

extra_css:
  - style.css

# Add watch directive to monitor Python source files
watch:
  - docs
  - mkdocs.yaml
  - gpac

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          # Use the extended handler instead of the default one
          handler: python_xref
          # Regular mkdocstrings options go here
          options:
            show_source: true
            show_root_heading: true
            
# plugins:
#   - search
#   - autorefs  # This must be before mkdocstrings
#   - mkdocstrings:
#       default_handler: python_xref
#       handlers:
#       python_xref:
#         import:
#         - https://docs.python.org/3/objects.inv
#         options:
#           docstring_style: google
#           docstring_options:
#             ignore_init_summary: yes
#           merge_init_into_class: yes
#           relative_crossrefs: yes
#           check_crossrefs: no
#           separate_signature: yes
#           show_source: no
#           show_root_full_path: no
      # default_handler: python
#       python:
#         options:
#           members_order: source
#           signature_crossrefs: true
#           show_if_no_docstring: false
#           separate_signature: true
#           show_signature_annotations: true
#           docstring_section_style: table
#           show_symbol_type_heading: true
#           docstring_style: numpy
#           docstring_options:
#             ignore_init_summary: true
#             preserve_newlines: true
#             enable_relative_crossref: true
#           line_length: 100
# #            merge_init_into_class: true # don't want to display autogenerated __init__ method for Summary
#                                         # since it's supposed to be created using the from_file method
#           show_submodules: true
#           selection:
#             members:
#               - gpac
#               - Summary
nav:
  - Home: index.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

# This is needed to render Latex even though we included arithmatex above.
extra_javascript:
  - mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js